### ISSUE TITLE
Mobile - Scorrimento automatico in booktober non funziona

### ISSUE THREAD

**Issue by GicoProgram** [booksheartbrain/booksheartbrain#11]

**Comment by GicoProgram** [comment]
Issue dovuta a firefox mobile, non al sito. Con altro browser mobile funziona, probabile chiusura issue a breve.

Counter segnala pochi accessi da Firefox, quindi risoluzioni troppo complicate sarebbero inutili per la maggior parte dei visitatori

**Comment by booksheartbrain** [comment]
Chiusura issue, risoluzione non possibile
